In [1]:
import numpy as np
print(f'NumPy version = {np.__version__}')

NumPy version = 1.19.5


In [2]:
a = np.random.randint(140, 200, 10)
a

array([164, 149, 169, 174, 141, 148, 171, 140, 179, 145])

In [3]:
print(a.shape)
print(a.size)
print(a.ndim)

(10,)
10
1


In [5]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a[:3]

array([0, 1, 2])

In [7]:
a[-1]

9

In [8]:
a[4:]

array([4, 5, 6, 7, 8, 9])

In [9]:
a[2:5]

array([2, 3, 4])

In [10]:
a[::2]

array([0, 2, 4, 6, 8])

In [11]:
a[::3]

array([0, 3, 6, 9])

In [12]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [13]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a[-3:] # last 3 elements

array([7, 8, 9])

In [15]:
a[-4:-1]

array([6, 7, 8])

In [16]:
b = np.array(['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto'])
b

array(['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus',
       'Neptune', 'Pluto'], dtype='<U7')

In [17]:
b[2]

'Earth'

# **shoe size**
https://en.wikipedia.org/wiki/Shoe_size#Size_conversion

In [18]:
a = np.array(['EUR','Mondo','UK','US men','US women'])
a

array(['EUR', 'Mondo', 'UK', 'US men', 'US women'], dtype='<U8')

In [19]:
np.argwhere(a == 'UK')

array([[2]])

In [20]:
np.where(a == 'UK')

(array([2]),)

In [21]:
shoe_size = np.array([[34,215,2,3,4],[34.5,215,2.5,3.5,4.5],[35,220,3,4,5],[35.5,225,3.5,4.5,5.5],[36,225,4,5,6],[36.5,230,4,5,6],[37,235,4.5,5.5,6.5],[37.5,235,5,6,7],[38,240,5.5,6.5,7.5],[38.5,245,5.5,6.5,7.5],[39,245,6,7,8],[39.5,250,6.5,7.5,8.5],[40,255,7,8,9],[40.5,255,7.5,8.5,9.5],[41,260,7.5,8.5,9.5],[41.5,265,8,9,10],[42,265,8.5,9.5,10.5],[42.5,270,9,10,11],[43,275,9.5,10.5,11.5],[43.5,275,9.5,10.5,11.5],[44,280,10,11,12],[44.5,285,10.5,11.5,12.5],[45,285,11,12,13],[45.5,290,11.5,12.5,13.5],[46,295,11.5,12.5,13.5],[46.5,295,12,13,14],[47,300,12.5,13.5,14.5],[47.5,305,13,14,15],[48,305,13,14,15],[48.5,310,13.5,14.5,15.5],[49,315,14,15,16],[49.5,315,14.5,15.5,16.5],[50,320,15,16,17]])

In [22]:
shoe_size

array([[ 34. , 215. ,   2. ,   3. ,   4. ],
       [ 34.5, 215. ,   2.5,   3.5,   4.5],
       [ 35. , 220. ,   3. ,   4. ,   5. ],
       [ 35.5, 225. ,   3.5,   4.5,   5.5],
       [ 36. , 225. ,   4. ,   5. ,   6. ],
       [ 36.5, 230. ,   4. ,   5. ,   6. ],
       [ 37. , 235. ,   4.5,   5.5,   6.5],
       [ 37.5, 235. ,   5. ,   6. ,   7. ],
       [ 38. , 240. ,   5.5,   6.5,   7.5],
       [ 38.5, 245. ,   5.5,   6.5,   7.5],
       [ 39. , 245. ,   6. ,   7. ,   8. ],
       [ 39.5, 250. ,   6.5,   7.5,   8.5],
       [ 40. , 255. ,   7. ,   8. ,   9. ],
       [ 40.5, 255. ,   7.5,   8.5,   9.5],
       [ 41. , 260. ,   7.5,   8.5,   9.5],
       [ 41.5, 265. ,   8. ,   9. ,  10. ],
       [ 42. , 265. ,   8.5,   9.5,  10.5],
       [ 42.5, 270. ,   9. ,  10. ,  11. ],
       [ 43. , 275. ,   9.5,  10.5,  11.5],
       [ 43.5, 275. ,   9.5,  10.5,  11.5],
       [ 44. , 280. ,  10. ,  11. ,  12. ],
       [ 44.5, 285. ,  10.5,  11.5,  12.5],
       [ 45. , 285. ,  11. ,  12

In [23]:
shoe_size[2]

array([ 35., 220.,   3.,   4.,   5.])

In [24]:
shoe_size[:, 2]

array([ 2. ,  2.5,  3. ,  3.5,  4. ,  4. ,  4.5,  5. ,  5.5,  5.5,  6. ,
        6.5,  7. ,  7.5,  7.5,  8. ,  8.5,  9. ,  9.5,  9.5, 10. , 10.5,
       11. , 11.5, 11.5, 12. , 12.5, 13. , 13. , 13.5, 14. , 14.5, 15. ])

In [25]:
shoe_size[:, 0] == 41

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [26]:
shoe_size[shoe_size[:, 0] == 41]

array([[ 41. , 260. ,   7.5,   8.5,   9.5]])

In [27]:
shoe_size[:, 1:][shoe_size[:, 0] == 41]

array([[260. ,   7.5,   8.5,   9.5]])

In [28]:
shoe_size[:, 3][shoe_size[:, 0] == 41]


array([8.5])

In [29]:
shoe_size[:, 3][shoe_size[:, 0] == 41]

array([8.5])

In [30]:
a

array(['EUR', 'Mondo', 'UK', 'US men', 'US women'], dtype='<U8')

In [31]:
i, = np.where(a == 'UK')
i

array([2])

In [32]:
shoe_size[:, np.where(a == 'US men')][shoe_size[:, 0] == 41]

array([[[8.5]]])

In [33]:
a[2]

'UK'

In [34]:
a[i]

array(['UK'], dtype='<U8')

In [35]:
i, = np.where((a == 'UK') | (a == 'US men'))
i

array([2, 3])

In [36]:
shoe_size[:, np.where((a == 'UK') | (a == 'US men'))][shoe_size[:, 0] == 41]

array([[[7.5, 8.5]]])